# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TiCloudRTCObjcExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for TiCloudRTCObjcExample

#  pod 'TiCloudRTC', '3.2.7'
  
  # YTKNetworking
  pod 'YTKNetwork'
  
  # 网络库
  pod 'AFNetworking'

  # YYModel
  pod 'YYModel'
  pod 'YYCategories'
  
  #弹出菜单  https://github.com/lyb5834/YBPopupMenu
  pod 'YBPopupMenu'

  #标签https://github.com/zekunyan/TTGTagCollectionView
  pod "TTGTagCollectionView",'1.11.1'
  
  #吐司
  pod 'MBProgressHUD'
  
  #RAC
  pod 'ReactiveObjC'
  
  #下拉刷新
  pod 'MJRefresh'
  
  #圆角处理
  pod 'ZYCornerRadius'
  
  #UISegmentedControl
  pod 'WMPageController'
  
  
  pod 'AgoraRtm_iOS', '1.5.1'
#      pod 'AgoraAudio_iOS/RtcBasic', '4.1.1'
  pod 'AgoraAudio_Special_iOS', '4.1.1.17.BASIC'
  
#  post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      target.build_configurations.each do |config|
#        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
#          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#        end
#      end
#    end
#  end


  target 'TiCloudRTCObjcExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TiCloudRTCObjcExampleUITests' do
    # Pods for testing
  end

end
